name: neuralflow
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cudatoolkit=11.2
  - cudnn=8.1
  - jax
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pip
  - pytest
  - scipy
  - scikit-learn
  - tqdm
  - pip:
      - https://storage.googleapis.com/jax-releases/cuda112/jaxlib-0.1.65+cuda112-cp39-none-manylinux2010_x86_64.whl
